### PR TITLE
Daemon/App: initialize contexts *after* fork + various refactoring. Fixes #312

### LINKED ISSUE #214: Config options: implementation and cleanup work
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---
- [X] 1. Clarify/cleanup config options/descriptions
- [X] 2. Implement `--log-to-console` `--log-to-file` `--log-file-name`
- [x] 3. Implement ability to log to `--log-file-to-file` when in daemon mode
- [x] 4. Update/document configuration file

---

As reported in IRC:
- [X] `--log` should also be reimplemented to `--log-to-console`/`--log-to-file` to enable/disable console or file log output
- [X] We need a `--log-to-file` that will actually log to a file so we don't have to `$ kovri 2>&1 >/dev/null | tee logfile`
- [X] We should consolidate many of the config options into only a few categories and remove `-w` switch as its confusing (`--help-with` is fine for now)
- [x] `--service` description need clarification/updating
- [x] In daemon mode, kovri won't output any logging except for a handful of intro info messages. Be sure that once #312 is resolved, we should implement the ability to `--log--to-file` even when in daemon mode
- [x] Options given on the commandline should instead be clearly documented within the configuration file

Referencing #96.

### LINKED ISSUE #312: Segfault when running in daemon mode
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Tested + reproducible on:
- Ubuntu 16.04, (gcc 5.4.0)
- Arch Linux (gcc 6.1.1)
- OSX (Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn))

Running`./build/kovri/ -d1` with regular `make` against b310b19.

GDB backtrace [attached](https://github.com/monero-project/kovri/files/422486/daemon_backtrace.txt).

OSX produces (did not run LLDB):

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```

Daemon mode was fully functional when I opened #214 but building against b078bd5 produces the same results.

**Edit**: side-note and possibly not related: there have been multiple issues in the past when in daemon mode and the daemon-related code is just terrible - as is the singleton tied into it.

### PR DESCRIPTION
**Pull request by anonimal**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [X] I confirm.

---

Fixes #312, closes #214, references #98

### CODE REVIEW

File: src/app/util/config.cc [hunk 1]
```diff
@@ -173,12 +175,16 @@ bool SetLoggingOptions() {
...
-  log::SetGlobalLogLevels(arg_levels);
+  core::SetGlobalLogLevels(arg_levels);
   // Set other logging options
-  log::SetOptionLogToConsole(var_map["log-to-console"].as<bool>());
-  // TODO(anonimal): hack to ensure log-to-console is enabled in daemon mode
-  log::SetOptionLogToFile(var_map["log-to-file"].as<bool>());
-  log::SetOptionLogFileName(var_map["log-file-name"].as<std::string>());
+  core::SetOptionLogToConsole(VarMap["log-to-console"].as<bool>());
+  // TODO(unassigned): the following daemon test is a HACK to ensure that
+  // log-to-console is enabled in daemon mode (or else we'll boost.log segfault)
```
Comment (anonimal) [inline src/app/util/config.cc]: Note: with `log-to-console` enabled, only the first handful of lines of output will be sent to console (in the parent process) before forking. File logging will remains intact throughout.
