### PR TITLE
TunnelHopConfig + I/O ByteStream: fixes + refactoring + documentation. Closes #355

### LINKED ISSUE #355: TunnelHopConfig: SIGSEGV when creating build request record
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Current tunnel design = :hankey: and there are many pointer assumptions in this spaghetti code _but_ this segfault is likely caused by an improperly initialized router identity.

**Edit:** built against 00e0dfe6ce1b458cf28bd453b858b1f57fbe4200 but observed sporadically for as long as I can remember.

```
$ gdb build/kovri
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
...

Thread 15 "kovri" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe89c5700 (LWP 20801)]
0x00000000010d56f2 in i2p::tunnel::TunnelHopConfig::CreateBuildRequestRecord (this=0x7fffcc05e850, record=0x7fffcc0f2393 "", replyMsgID=1742868940) at /home/anonimal/kovri/src/core/tunnel/tunnel_config.cc:107
107           router->GetIdentHash(),
(gdb) bt
#0  0x00000000010d56f2 in i2p::tunnel::TunnelHopConfig::CreateBuildRequestRecord (this=0x7fffcc05e850, record=0x7fffcc0f2393 "", replyMsgID=1742868940) at /home/anonimal/kovri/src/core/tunnel/tunnel_config.cc:107
#1  0x00000000010c1bfe in i2p::tunnel::Tunnel::Build (this=0x7fffcc10d900, replyMsgID=1742868940, outboundTunnel=std::shared_ptr (empty) 0x0) at /home/anonimal/kovri/src/core/tunnel/tunnel.cc:89
#2  0x00000000010c81fa in i2p::tunnel::Tunnels::CreateTunnel<i2p::tunnel::InboundTunnel> (this=0x163b900 <i2p::tunnel::tunnels>, config=std::shared_ptr (count 2, weak 1) 0x7fffcc06c1b0, outboundTunnel=std::shared_ptr (empty) 0x0)
    at /home/anonimal/kovri/src/core/tunnel/tunnel.cc:698
#3  0x00000000010c4781 in i2p::tunnel::Tunnels::ManageInboundTunnels (this=0x163b900 <i2p::tunnel::tunnels>) at /home/anonimal/kovri/src/core/tunnel/tunnel.cc:648
#4  0x00000000010c3bc8 in i2p::tunnel::Tunnels::ManageTunnels (this=0x163b900 <i2p::tunnel::tunnels>) at /home/anonimal/kovri/src/core/tunnel/tunnel.cc:500
#5  0x00000000010c38e6 in i2p::tunnel::Tunnels::Run (this=0x163b900 <i2p::tunnel::tunnels>) at /home/anonimal/kovri/src/core/tunnel/tunnel.cc:465
#6  0x00000000010d503f in std::_Mem_fn_base<void (i2p::tunnel::Tunnels::*)(), true>::operator()<, void>(i2p::tunnel::Tunnels*) const (this=0x16b6f88, __object=0x163b900 <i2p::tunnel::tunnels>) at /usr/include/c++/5/functional:600
#7  0x00000000010d4f93 in std::_Bind<std::_Mem_fn<void (i2p::tunnel::Tunnels::*)()> (i2p::tunnel::Tunnels*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x16b6f88, 
    __args=<unknown type in /home/anonimal/kovri/build/kovri, CU 0xff0721, DIE 0x1087508>) at /usr/include/c++/5/functional:1074
#8  0x00000000010d4ee9 in std::_Bind<std::_Mem_fn<void (i2p::tunnel::Tunnels::*)()> (i2p::tunnel::Tunnels*)>::operator()<, void>() (this=0x16b6f88) at /usr/include/c++/5/functional:1133
#9  0x00000000010d4eae in std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::tunnel::Tunnels::*)()> (i2p::tunnel::Tunnels*)> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x16b6f88) at /usr/include/c++/5/functional:1531
#10 0x00000000010d4d40 in std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::tunnel::Tunnels::*)()> (i2p::tunnel::Tunnels*)> ()>::operator()() (this=0x16b6f88) at /usr/include/c++/5/functional:1520
#11 0x00000000010d4bd0 in std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::tunnel::Tunnels::*)()> (i2p::tunnel::Tunnels*)> ()> >::_M_run() (this=0x16b6f70) at /usr/include/c++/5/thread:115
#12 0x00007ffff58b7c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff6b0f6fa in start_thread (arg=0x7fffe89c5700) at pthread_create.c:333
#14 0x00007ffff501db5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```

While we're here, see also [CID 141387](https://github.com/monero-project/kovri/issues/263).

### LINKED ISSUE #366: Rewrite Identity implementation
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

If I had to vote for one of the most questionably dangerous, ugliest, least functional, and least maintainable areas of this codebase, I could give a strong vote for our current identity implementation. It's error prone and confusing (to say the least). It's not a lot of code but it's important code - so it should be solid code (as should the other areas that tie into it).

Noticed especially during #364, we can put this issue toward a later release milestone but ideas for improvements in the meantime are welcome. One solution includes over-arching libcore design refactor but let's not get carried away (for now) 😄

### PR DESCRIPTION
**Pull request by anonimal**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [X] I confirm.

---

Regarding #355, if the issue is a null router info, this branch should deal appropriately. If (as mentioned in ticket) the issue is indeed a null router identity, then I'll need a real backtrace because there is nothing glaringly obvious outside of painfully convoluted tunnel code and the need to resolve #366.

Live tests pass. Closes #355

### CODE REVIEW

File: src/core/util/byte_stream.cc [hunk 1]
```diff
@@ -60,55 +61,77 @@ std::uint8_t* InputByteStream::ReadBytes(
...
 void OutputByteStream::WriteUInt32(std::uint32_t data) {
-  std::uint8_t buf[4] = {};
+  std::uint8_t buf[sizeof(std::uint32_t)] = {};
   htobe32buf(buf, data);
   WriteData(buf, sizeof(buf));
 }
 
+void OutputByteStream::WriteUInt64(std::uint64_t data) {
+  std::uint8_t buf[sizeof(std::uint64_t)] = {};
+  htobe64buf(buf, data);
```
Comment (vtnerd) [inline src/core/util/byte_stream.cc]: A minor point to already written code - seems like it would've been easier to return `std::array<std::uint8_t, SIZE>`, not sure of any advantages to the output argument.

File: src/core/util/byte_stream.cc [hunk 2]
```diff
@@ -60,55 +61,77 @@ std::uint8_t* InputByteStream::ReadBytes(
...
+  WriteData(buf, sizeof(buf));
+}
+
 std::uint8_t* OutputByteStream::GetPosition() const {
   return m_Data;
 }
 
+std::uint8_t* OutputByteStream::GetData() const {
```
Comment (vtnerd) [inline src/core/util/byte_stream.cc]: I could've stated this in a number of places - place these in the header? This will not require any additional includes in the header, and the compiler can inline simple functions that amount to `this + offsetof(...)` without having  to enable complicated LTO. I would only consider putting these definitions in the cpp if an actual copy constructor has to be called.

File: src/core/util/byte_stream.h [hunk 3]
```diff
@@ -138,11 +143,26 @@ class OutputByteStream {
...
 
-  uint8_t* GetPosition() const;
+  /// @brief Writes a 64-bit unsigned integer type into buffer
+  /// @note Converts bytes from host to big-endian order
+  /// @note Increments buffer pointer position after writing data
+  /// @param data Data to write
+  void WriteUInt64(std::uint64_t data);
+
+  /// @brief Get current pointer position of written data
+  std::uint8_t* GetPosition() const;
```
Comment (vtnerd) [inline src/core/util/byte_stream.h]: Are these supposed to be pointers to mutable data? Would `const std::uint8_t*` be better?

File: src/core/router/tunnel/config.cc [hunk 4]
```diff
@@ -32,134 +32,205 @@
...
-  prev = p;
-  if (prev) {
-    prev->next = this;
-    prev->is_endpoint = false;
-    is_gateway = false;
+TunnelHopConfig* TunnelHopConfig::GetNextHop() const noexcept {
+  return m_NextHop;
+}
+
+void TunnelHopConfig::SetPreviousHop(TunnelHopConfig* hop) noexcept {
```
Comment (vtnerd) [inline src/core/router/tunnel/config.cc]: Why provide this function? This seems to basically be an alias of the other function, and I do not see where this is being called.

File: src/core/router/tunnel/config.cc [hunk 5]
```diff
@@ -32,134 +32,205 @@
...
+void TunnelHopConfig::SetReplyHop(const TunnelHopConfig* hop) {
+  if (!hop)
+    throw std::runtime_error("TunnelHopConfig: reply hop is null");
+  SetNextRouter(hop->GetCurrentRouter(), hop->GetTunnelID(), true);
+}
+
+void TunnelHopConfig::SetNextHop(TunnelHopConfig* hop) {
+  m_NextHop = hop;
+  if (m_NextHop) {
+    m_NextHop->m_PreviousHop = this;
```
Comment (vtnerd) [inline src/core/router/tunnel/config.cc]: Presumably this is why a raw ptr was chosen over a `shared_ptr` (cyclic reference) - what about a `weak_ptr`? Lifetime has to be mandated externally, which can be tough for larger projects sometimes ...

I saw how this was constructed after reading some more of the code. What if `setNextHop` took a `unique_ptr` - it would obvious that it was taking ownership of the `hop`.

File: src/core/router/tunnel/config.cc [hunk 6]
```diff
@@ -168,17 +239,15 @@ TunnelConfig::TunnelConfig(
   for (auto it : peers) {
     auto hop = new TunnelHopConfig(it);
```
Comment (vtnerd) [inline src/core/router/tunnel/config.cc]: Might be a good time to make this a `unique_ptr<...>`

File: src/core/router/tunnel/config.cc [hunk 7]
```diff
@@ -232,14 +301,14 @@ void TunnelConfig::Print(
   TunnelHopConfig* hop = m_FirstHop;
   if (!IsInbound())  // outbound
     s << "me";
-  s << "-->" << m_FirstHop->tunnel_ID;
+  s << "-->" << m_FirstHop->GetTunnelID();
   while (hop) {
-    s << ":" << hop->router->GetIdentHashAbbreviation() << "-->";
-    if (!hop->is_endpoint)
-      s << hop->next_tunnel_ID;
+    s << ":" << hop->GetCurrentRouter()->GetIdentHashAbbreviation() << "-->";
```
Comment (vtnerd) [inline src/core/router/tunnel/config.cc]: This can return `nullptr` ... ?

File: src/core/router/tunnel/impl.cc [hunk 8]
```diff
@@ -136,42 +136,44 @@ bool Tunnel::HandleTunnelBuildResponse(
...
   bool established = true;
   hop = m_Config->GetFirstHop();
   while (hop) {
     const std::uint8_t* record =
-      msg + 1 + hop->record_index * TUNNEL_BUILD_RECORD_SIZE;
+      msg + 1 + hop->GetRecordIndex() * TUNNEL_BUILD_RECORD_SIZE;
     std::uint8_t ret = record[BUILD_RESPONSE_RECORD_RET_OFFSET];
     LogPrint(eLogDebug, "Tunnel: ret code=", static_cast<int>(ret));
-    hop->router->GetProfile()->TunnelBuildResponse(ret);
+    hop->GetCurrentRouter()->GetProfile()->TunnelBuildResponse(ret);
```
Comment (vtnerd) [inline src/core/router/tunnel/impl.cc]: Potential `nullptr` ... ?

File: src/core/router/tunnel/impl.h [hunk 9]
```diff
@@ -135,11 +135,11 @@ class Tunnel : public TunnelBase {
       std::shared_ptr<I2NPMessage> out);
 
   std::uint32_t GetNextTunnelID() const {
-    return m_Config->GetFirstHop()->tunnel_ID;
+    return m_Config->GetFirstHop()->GetTunnelID();
   }
 
   const kovri::core::IdentHash& GetNextIdentHash() const {
-    return m_Config->GetFirstHop()->router->GetIdentHash();
+    return m_Config->GetFirstHop()->GetCurrentRouter()->GetIdentHash();
```
Comment (vtnerd) [inline src/core/router/tunnel/impl.h]: `nullptr` .... ?

File: src/core/router/tunnel/config.cc [hunk 10]
```diff
@@ -32,134 +32,205 @@
...
+      m_AESRecordAttributes(),
+      m_NextRouter(nullptr),
+      m_NextTunnelID(0),
+      m_PreviousHop(nullptr),
+      m_NextHop(nullptr),
+      m_IsGateway(true),
+      m_IsEndpoint(true),
+      m_RecordIndex(0) {
+        if (!router)
+          throw std::runtime_error("TunnelHopConfig: current router is null");
```
Comment (anonimal) [inline src/core/router/tunnel/config.cc]: Yes, it's more appropriate.

File: src/core/router/tunnel/config.cc (hunk 5 above)
Comment (anonimal) [inline src/core/router/tunnel/config.cc]: The lack of smart pointers have always been an issue with this codebase but I/we've been refactoring along the way. Referencing #511

File: src/core/router/tunnel/config.cc (hunk 4 above)
Comment (anonimal) [inline src/core/router/tunnel/config.cc]: It's useless at the moment but was implemented for continuity. If it's dead for too long we should remove it. As for alias, I don't know where you're talking about. Setting the next hop is not the same as setting the previous hop.

File: src/core/router/tunnel/config.cc (hunk 6 above)
Comment (anonimal) [inline src/core/router/tunnel/config.cc]: As noted above, the lack of smart pointers have always been an issue with this codebase but I/we've been refactoring along the way. This kind of work was out of scope for this branch and it has repercussions elsewhere so, I chose not to touch this for now. Referencing #511.

File: src/core/router/tunnel/config.cc (hunk 7 above)
Comment (anonimal) [inline src/core/router/tunnel/config.cc]: Theoretically, yes. Current implementation: no (more eyes welcome though). Referencing #511.

File: src/core/util/byte_stream.cc (hunk 1 above)
Comment (anonimal) [inline src/core/util/byte_stream.cc]: I can see @EinMByte arguing against template code in this area (I agree with him on that so far) - but I 100% agree with you @vtnerd for most other areas.

File: src/core/util/byte_stream.cc (hunk 2 above)
Comment (anonimal) [inline src/core/util/byte_stream.cc]: @EinMByte wrote these bytestream classes, so maybe he has his reasons. As for `TunnelHopConfig`, I almost *always* place getters/setters in header but I specifically chose not to for `TunnelHopConfig` purely out of aesthetics and maintainability (tunnel logic is tricky at times and I needed a clean slate to work on). I'm flexible in either case though because #511 is now open and there is a good trade-off in favor of optimization in this area.

File: src/core/util/byte_stream.h (hunk 3 above)
Comment (anonimal) [inline src/core/util/byte_stream.h]: Doing so would produce invalid conversions elsewhere. We'd have to review those areas because those definitions could probably be updated.

File: src/core/router/tunnel/impl.cc (hunk 8 above)
Comment (anonimal) [inline src/core/router/tunnel/impl.cc]: Theoretically, yes. Current implementation: no (more eyes welcome though). Referencing #511.

File: src/core/router/tunnel/impl.h (hunk 9 above)
Comment (anonimal) [inline src/core/router/tunnel/impl.h]: Theoretically, yes. Current implementation: no (more eyes welcome though). Referencing #511.

**Comment by anonimal** [comment]
Thank you @vtnerd 👍

File: src/core/util/byte_stream.cc (hunk 2 above)
Comment (vtnerd) [inline src/core/util/byte_stream.cc]: How are getters in the header more maintenance? The aesthetics is interesting - it makes the header cleaner and the cpp worse. Modern module based systems (Rust, etc) are better in this area sadly.

Comment (anonimal) [inline src/core/util/byte_stream.cc]: >How are getters in the header more maintenance?

They usually aren't but maybe consider approaching this refactor from the initial angle with all other *non-semantics* and other considerations in place (big picture tunnel design, I2P tunnel design).

Also note that none of this is set in stone and this is all a work in progress.  Cleaner header file or implementation file - at that point, it's splitting hairs 😄

File: src/core/util/byte_stream.cc (hunk 1 above)
Comment (anonimal) [inline src/core/util/byte_stream.cc]: No but, because of the frequency of these calls and the use-case, IMHO, this area doesn't warrant the extra overhead (even if it is tiny).

Comment (vtnerd) [inline src/core/util/byte_stream.cc]: What overhead would you expect? The possible code generation bloat (i.e. the assembly for the conversion is generated + inlined multiple times)? I wouldn't expect the number of instructions generated for that function to be very high anyway, but I have spent an excessive amount of time on server CPUs which has warped my thinking of cache sizes.

Anyway, I wrote this comment before I got to look at the `OutputByteStream` as a whole. The better refactor (if needed) is to give the internal pointer directly to these conversion functions. It would remove one of the copies, which is always a performance gain (unless the compiler is slick enough to remove it already ...).

Comment (anonimal) [inline src/core/util/byte_stream.cc]: >I wouldn't expect the number of instructions generated for that function to be very high anyway

I think this is becoming a moot point. If this area bugs you enough, please feel free to PR.

Regardless, I must say that I'm glad to see that you're becoming more involved, so welcome. The more the merrier 🎉

Comment (vtnerd) [inline src/core/util/byte_stream.cc]: I was not trying to convince you to change anything, I was trying to understand what you meant. Was the overhead you referenced referring to general template bloat?

Comment (anonimal) [inline src/core/util/byte_stream.cc]: Yes, that was all.
